### ISSUE TITLE
Disparity between help and app around the optionality of "fruit"

### ISSUE THREAD

**Issue by globau** [hamvocke/root-loops#2]
I wanted to remove the tinting applied by the fruit, so I dug into the help.  Setting the sogginess to 0 did the trick.

However, the help page implies that fruit is optional, which doesn't appear to be correct:
> If you didn't add any fruit, this ingredient won't have any effect. If you added some fruit, the sogginess is going to make the color you chose more or less vibrant.

**Comment by hamvocke** [comment]
Thanks, @globau! Fixed in [this commit](https://github.com/hamvocke/root-loops/commit/7b7eb53ca0a7e4672192e8c95afb8711083f6b92)
