### ISSUE TITLE
support for Zellij

### ISSUE THREAD

**Issue by tcoopman** [hamvocke/root-loops#21]
I think this should be not hard with the current theming possibilities of [zellij](https://github.com/zellij-org/zellij)

Here are some PRs that implement a theme: https://github.com/zellij-org/zellij/pull/3579 https://github.com/zellij-org/zellij/pull/3596

**Comment by hamvocke** [comment]
Closed by 9297c9ba1751f8b42f03bd7507e4cc2f11dcdf90
