### ISSUE TITLE
iTerm2 theme export

### ISSUE THREAD

**Issue by chayes72** [hamvocke/root-loops#48]
Being able to export to iTerm2 either as a single theme or dark/light mode would make importing themes a much easier process.

[Root Loops - Classic Ederberry No Milk (7:8:8).itermcolors.gz](https://github.com/user-attachments/files/17873875/Root.Loops.-.Classic.Ederberry.No.Milk.7.8.8.itermcolors.gz)

**Comment by hamvocke** [comment]
Donezo! 🙌
