### ISSUE TITLE
Add helix export

### ISSUE THREAD

**Issue by arjpar** [hamvocke/root-loops#6]
It would be useful to have an export to Helix editor. [Here] is the documentation for Helix themes: https://github.com/helix-editor/helix/blob/master/book/src/themes.md .  Let me know if you have any more questions or need some help/a PR, I can help out - I'm writing this in a rush!

**Comment by hamvocke** [comment]
Thanks for the request, @arjpar!

I've been building out the export functionality slowly over the last few weeks, starting with various terminal emulators. My very next step is to add exports for editors, and Helix is definitely on that list! After your request I might just move that to the very top of my priorities in fact. I had started investigating how I could export themes to vim/neovim and that took much more research effort than I originally expected.

It looks like Helix's theming approach is much simpler and probably a much better starting point.

Helix also ships with a few themes that simply inherit the 16 colors set by your terminal. If you want to use a root loops theme in Helix today, you could export your favorite scheme, apply it to your terminal emulator of choice, and set Helix to use one of the following color schemes:

* `base16-terminal`
* `base16-transparent`
* `term16-light`
* `term16-dark`

(You can basically pick any theme [from here](https://github.com/helix-editor/helix/tree/master/runtime/themes) that doesn't define a custom '[palette]' section).

**Comment by hamvocke** [comment]
Alright, I think we've got a good start. If you go to https://rootloops.sh you'll now see a Helix option in the "export" panel:

![scrn-2024-10-01-20-01-15](https://github.com/user-attachments/assets/9a1745f9-5eeb-46eb-b083-061bb0d059d0)

Have fun!
