### ISSUE TITLE
Add support for ghostty terminal

### ISSUE THREAD

**Issue by tcoopman** [hamvocke/root-loops#7]
Here you can find the format: https://github.com/ghostty-org/ghostty?tab=readme-ov-file#configuration

**Comment by tcoopman** [comment]
Good point, I forgot about that.
Ghostty is currently in private beta. I think the easiest is to ping @mitchellh@hachyderm.io - I can do that for you if you want.

**Comment by hamvocke** [comment]
I got access to the repo now. Looks like a pretty straightforward config. I'll take a stab at this in the next few days.

**Comment by hamvocke** [comment]
![scrn-2024-10-05-18-58-09](https://github.com/user-attachments/assets/48b50e1d-3913-4a32-91f6-7bbf97aa9971)

:ghost: :heavy_check_mark:
