### ISSUE TITLE
Add a "columns" like Terminal Preview to check foreground readability on colored backgrounds

### ISSUE THREAD

**Issue by crshrprt** [hamvocke/root-loops#9]
Would be useful to add a "columns" like Terminal Preview to check the readability of different foreground colors on colored backgrounds.

Example:
![columns](https://github.com/user-attachments/assets/70588f49-ca8a-421d-aa93-b231b50069db)

**Comment by hamvocke** [comment]
Great idea! I'll see what I can do here :+1:

**Comment by hamvocke** [comment]
![Columns on Root Loops](https://github.com/user-attachments/assets/c1262ff9-15d7-4c51-8a1a-d9a8f13808b8)

There we go!
